### ISSUE TITLE
상품목록에서 금액 부분 detail 부분과 상이함

### ISSUE THREAD

**Issue by yoo94** [FC-InnerCircle/icd01-team05_06-commerce-fe#40]
## 🔍️ 이 ISSUE을 통해 해결하려는 문제가 무엇인가요? (필수사항)

> book-card.tsx 고칠때 book.discount로 해서 그런것같습니다.
> 
![image](https://github.com/user-attachments/assets/af766bcf-a70f-4e3d-9876-c170b6fa95d4)
![image](https://github.com/user-attachments/assets/f23adadd-0f0a-4378-a910-2605607f5cfa)

## ✨ 이 ISSUE에서 핵심적으로 변경된 사항은 무엇일까요? (필수사항)

> 금액은 book.price - book.discount 으로 해야할것 같습니다.

# 제가 고쳐도 되는 부분인지를 몰라서 일단 이슈로 남겨놓겠습니다.
@zel0rd  영길님 부분이지만..
@dvlpDana  단비님이 변경해놓으신 부분이라

**Comment by dvlpDana** [comment]
....죄송합니다...ㅎㅎ 제가 괜히 수정을 해놔서 이 사단이 났네요;; 찾아봐주셔서 감사합니다 재석님 ㅎㅎㅎ 저번에도 어떻게 할지 논의되었던 부분인거 같긴한데 discount를 할인 금액으로 볼지, 아니면 discount를 할인이 적용된 가격으로 볼지를 정하면 될 거 같습니당 ㅎㅎㅎ
